### ISSUE TITLE
Empty Graph for some users

### ISSUE THREAD

**Issue by josemontesdeoca** [CodePath-MAF/AndroidClient#111]
It might have to do with the order of the transactionGroup. We need to make sure the List is already ordered Date descending (Recent to oldest)

**Comment by fcduarte** [comment]
@josemontesdeoca taking a look right now.. I'll do the following:
1. Always have 7 bars
2. Get the first day of transactions list and create 7 bars from there
3. Iterate through transactions list and try to find the days there

**Comment by josemontesdeoca** [comment]
@fcduarte:

1) :+1: 
2 & 3) we can take advantage of Parse Cloud Code, to fetch the necessary data per day such that we only iterate and set up the bar objects and the chart.

Michael is working on a Cloud Code function that will return an Array of days that inside has the array breakdown of categories and amounts.

**Comment by josemontesdeoca** [comment]
@fcduarte should we close this?

**Comment by fcduarte** [comment]
sure!

2014-08-04 13:57 GMT-07:00 Jose Montes de Oca notifications@github.com:
