### ISSUE TITLE
User can view their Profile

### ISSUE THREAD

**Issue by josemontesdeoca** [CodePath-MAF/AndroidClient#22]
User can view its profile page and change information. See mocks: https://www.flinto.com/p/a0de3ed3

This requires:
- Create View (activity & xml)
- Get the current user from parse and display it.
- User can change:
  - Name
  - Profile image (potentially use the camera and/or gallery intent?)
  - Logout
  - password?

Note: Is not quite clear what can be changeable. It would be good to sync with the greater team and designers to agree upon what we want to do here as it will probably affect the data model a bit (Profile Image)

**Comment by fcduarte** [comment]
Closed by #45
