### ISSUE TITLE
User can add a payment to the Goal

### ISSUE THREAD

**Issue by josemontesdeoca** [CodePath-MAF/AndroidClient#24]
User can track the payments (savings) being made to a goal. 

This its trigger from the Goal View on the upper "plus" element shown on the action bar. Interaction can be seen on the mocks: https://www.flinto.com/p/a0de3ed3

This will require:
- Set up the view
- Trigger the activity
- Save the payment made in parse (In the same Transaction table just that it has a goal associated)
  - this will be a debit transaction and affect the users liquid asset balance.
- show a successful payment saved in the Goal view.

**Comment by amitbharadwaj** [comment]
Latest pull request of branch goal-view has these changes.

**Comment by fcduarte** [comment]
Closing the issue. If we find any problem let's create a new one.
