### ISSUE TITLE
Choose & implement a graphing library to use

### ISSUE THREAD

**Issue by josemontesdeoca** [CodePath-MAF/AndroidClient#28]
We need to have an Android graphing library which will allow us to provide financial graphs to better display data (Check out [Liquid Asset view mocks](https://www.flinto.com/p/a0de3ed3) for place where graphics may end up).

Library should allow us to properly display bar, pie, ..., charts

**Comment by fcduarte** [comment]
For now I chose [HoloGraphLibrary](https://bitbucket.org/danielnadeau/holographlibrary) with can be viewed at PR #31

**Comment by fcduarte** [comment]
HoloGraphLibrary is doing its job.
