### ISSUE TITLE
User can choose a goal and get detail view of it

### ISSUE THREAD

**Issue by josemontesdeoca** [CodePath-MAF/AndroidClient#29]
From the main dashboard, the user can click on a Goal box which will point him to a detail view. (View [mocks](https://www.flinto.com/p/a0de3ed3) for interactions)

This will require:
- Click a goal within the dashboard to trigger an intente to a new activity.
- Show detail view of upcoming payment
- Set up a fragment for the list of past payments:
  - List view with "endless scrolling" 
  - set up Custom Array Adapter and payment item xml

**Comment by amitbharadwaj** [comment]
This is done.
