### ISSUE TITLE
Create Goal View

### ISSUE THREAD

**Issue by josemontesdeoca** [CodePath-MAF/AndroidClient#3]
- Create Goal Activity View Layout, see [wireframe](https://github.com/CodePath-MAF/SharedAssets/blob/master/wireframes/PNG/Flow1%2B2/Lending_Circle%20.png) for ref
  - Mock data
- Create Past payments (transactions) View. 
  - Note: there is no wireframes for this yet (designers will provide on Thursday)

**Comment by amitbharadwaj** [comment]
To discuss:  decide whether to use support action bar or action bar sherlock
 @josemontesdeoca @fcduarte

**Comment by fcduarte** [comment]
I prefer the Support Action bar .. I would only choose Action Bar Sherlock if there is something that the Support Action Bar can't do

**Comment by josemontesdeoca** [comment]
Agree with @fcduarte. Lets go stock unless there's something we need to achieve not available with the Support Action Bar.

**Comment by amitbharadwaj** [comment]
Goal view is created. Styling of payments remain. Before that I would create model to handle payments. Pushing payments to next sprint.
