### ISSUE TITLE
[Android Bootcamp] Group Project - Review Sprint #2

### ISSUE THREAD

**Issue by josemontesdeoca** [CodePath-MAF/AndroidClient#30]
PTAL at [2nd sprint](https://github.com/CodePath-MAF/AndroidClient/issues?milestone=2&state=open). Any feedback is much appreciated.

/cc @nesquena @thecodepath @nidhi1608

**Comment by nidhi1608** [comment]
:+1: Impressive work so far on the group project. Your team has made great progress compared to where group projects have historically been at this point during the course. Hope you are proud of what you have achieved in ~5 weeks. 
- Good plan, overall strategy and work distribution. Your goals look realistic and if you continue working at this pace, your team should have a pretty good functional app by Sunday night.
- Keep working on integrating the core flows and make sure all pieces fit together perfectly.
- Consider improving your test coverage by incorporating positive as well as negative testing to determine if your app handles improper user behavior correctly.
- Consult with your mentors to get their feedback as often as you can. Remember they are here to help!

Please remember to submit the GIF walkthrough of your functional app latest by Sunday night. I would also encourage you to start thinking about coming up with a user story for the demo day. It is the apps with the most  appealing story that gains the most attention on the demo day. Looking forward to seeing your submission this Sunday!
