### ISSUE TITLE
Set up Test suite

### ISSUE THREAD

**Issue by josemontesdeoca** [CodePath-MAF/AndroidClient#36]
Lets try to set up some basic Android testing that would allow us to do a quick check every time we need to do a merge.

@fcduarte assigning to you to see if you had any experience or knowledge from work that we could use here. I'll also do investigation on this.

**Comment by fcduarte** [comment]
My experience tells me that it's awesome to have but it's difficult as hell
to do .. Not sure if we could came up with something before the end of the
sprints .. Anyway let's see how our velocity goes and then we could try
something if we have some available time.

2014-07-10 15:53 GMT-07:00 Jose Montes de Oca notifications@github.com:

**Comment by josemontesdeoca** [comment]
sg. thanks for sharing your experience. I knew you had a bit more exposure to make a more inform conclusion of the effort. :)
