### ISSUE TITLE
Create New Goal View

### ISSUE THREAD

**Issue by josemontesdeoca** [CodePath-MAF/AndroidClient#4]
- Prototype New Goal View (see [wireframe](https://github.com/CodePath-MAF/SharedAssets/blob/master/wireframes/PNG/Flow3/New_Goal_Amount.png))
- Save the goal against Parse.

**Comment by amitbharadwaj** [comment]
New goal view is created. Due date and frequency remains. Let's sync up on model for frequency and due date.
