### ISSUE TITLE
Create data models

### ISSUE THREAD

**Issue by josemontesdeoca** [CodePath-MAF/AndroidClient#5]
- Create POJOs for [schema](https://github.com/CodePath-MAF/SharedAssets/blob/master/schemas.md)
- Implement the [ParseObject subclasses](http://guides.codepath.com/android/Building-Data-driven-Apps-with-Parse#creating-parse-models)
- Populate parse with mock data
- Outline initial queries to satisfy:
  - Dashboard View
  - Liquid Assets View
  - Goal View (Past Payments)

**Comment by josemontesdeoca** [comment]
Initial models implemented in the following [commit](https://github.com/CodePath-MAF/AndroidClient/commit/f5e3911098b8b75955b5e609c4bd1365606f5875)

Remaining: Outline initial queries.

**Comment by josemontesdeoca** [comment]
I am marking this a close for the time being. @fcduarte & @amitbharadwaj Let me know if there is any problems with the models while doing the user stories.

The only thin missing is figure out the Goal "Type" property, thought is not a blocker as the wireframe does not use it.

**Comment by amitbharadwaj** [comment]
@josemontesdeoca we need goal frequency. Did we add that? We discussed an enum for frequency like monthly, weekly etc.
