### ISSUE TITLE
[Android Bootcamp] Group Project - Review Sprint #2 work

### ISSUE THREAD

**Issue by josemontesdeoca** [CodePath-MAF/AndroidClient#55]
Gif walkthrough to follow shortly.

PTAL at our 2nd sprint work. Any feedback is much appreciated.

/cc @nesquena @thecodepath @nidhi1608

**Comment by fcduarte** [comment]
First flow:
1. Sign up
2. Profile view/update
3. Logout
4. Login

![sign-up-flow](https://cloud.githubusercontent.com/assets/1507064/3566780/e62b52da-0b02-11e4-81ce-de7422439ce5.gif)

**Comment by fcduarte** [comment]
Second flow:
1. Dashboard
2. Liquid Assets Screen
3. Add Transaction

![liquid-asset-flow](https://cloud.githubusercontent.com/assets/1507064/3567018/4632ca88-0b0c-11e4-82fb-e4e8c487229c.gif)

**Comment by fcduarte** [comment]
Last flow:
1. Add new Goal
2. Detail Goal
3. Add Payment

![add-goal-flow](https://cloud.githubusercontent.com/assets/1507064/3567084/8759e382-0b0e-11e4-96c6-117660c3152e.gif)

**Comment by fcduarte** [comment]
Sprint 2 finished.
