### ISSUE TITLE
Add a default category for goal payments

### ISSUE THREAD

**Issue by fcduarte** [CodePath-MAF/AndroidClient#59]
It could be "Payment" for instance..

**Comment by josemontesdeoca** [comment]
I've added "Bills" as a category in parse (https://www.parse.com/apps/codepath-maf/collections#class/Category)

**Comment by josemontesdeoca** [comment]
@amitbharadwaj while storing the payment for a Goal make sure to add the following category to the transaction "Bills" (object id in parse: 93BaEoZPfo)

**Comment by amitbharadwaj** [comment]
just pushed this change in branch goal-view-polish
