### ISSUE TITLE
Add animated transitions according to mockups

### ISSUE THREAD

**Issue by fcduarte** [CodePath-MAF/AndroidClient#73]
### Animation 1: slide left

| From | To |
| --- | --- |
| Dashboard | Liquid Assets |
| Dashboard | Lending Circles |
| Dashboard | Goals |
### Animation 2: slide up

| From | To |
| --- | --- |
| Dashboard | Goal amount |
| Dashboard | Profile |
| Liquid Assets | Add Transaction |
| Lending Circles | Make Payment |

**Comment by amitbharadwaj** [comment]
fixed in PR #103
